import type { Metadata } from 'next'
import { CircleAlert, ShieldCheck } from 'lucide-react'
import { LanguageSwitcher } from '@/components/LanguageProvider'
import { RulesHero } from '@/components/RulesHero'
import { ProgramTabs } from '@/components/ProgramTabs'
import { RulesReadyCta } from '@/components/RulesReadyCta'

export const metadata: Metadata = {
  title: '2-Step Challenge Rules | FundedWealth Forex',
  description: 'Explore the complete FundedWealth Forex 2-Step Challenge Rules, including profit targets, drawdown limits, trading requirements, leverage, risk management, payouts, and trading conditions.',
}

const overview = [['8%', 'Stage 1 Profit Target'], ['5%', 'Stage 2 Profit Target'], ['5 Days', 'Minimum Trading Days\nPer Evaluation Stage'], ['7 Days', 'Funded Trading Days\nBefore payout eligibility'], ['5%', 'Maximum Daily Loss'], ['10%', 'Maximum Total Loss'], ['3%', 'Maximum Risk Per Trade\nFunded Stage'], ['Unlimited', 'Trading Period'], ['1:100', 'Forex Leverage'], ['1:30', 'Commodities Leverage'], ['1:2', 'Crypto Leverage'], ['80%', 'Funded Profit Split']]
const comparison = [['Virtual Balance', '$5,000 - $100,000', '$5,000 - $100,000', '$5,000 - $100,000'], ['Profit Target', '8%', '5%', 'No profit target'], ['Maximum Daily Loss', '5%', '5%', '5%'], ['Maximum Total Loss', '10%', '10%', '10%'], ['Maximum Risk Per Trade', 'N/A', 'N/A', '3%'], ['Minimum Trading Days', '5 trading days', '5 trading days', '7 trading days before payout eligibility'], ['Trading Period', 'Unlimited', 'Unlimited', 'Unlimited'], ['Forex Leverage', '1:100', '1:100', '1:100'], ['Commodities Leverage', '1:30', '1:30', '1:30'], ['Crypto Leverage', '1:2', '1:2', '1:2'], ['Profit Split', 'N/A', 'N/A', '80%']]

const detailedRules = [
  { title: 'Stage 1 Profit Target', body: <p>Reach an <strong>8% profit target</strong> during Stage 1 while remaining within all applicable risk limits. Close all open positions before progressing to Stage 2.</p> },
  { title: 'Stage 2 Profit Target', body: <p>After progressing to Stage 2, reach a <strong>5% profit target</strong> while remaining within all applicable risk limits. Close all open positions before qualifying for the funded account stage.</p> },
  { title: 'Minimum Trading Days', body: <><p>Complete at least <strong>5 qualifying trading days</strong> in Stage 1 and at least <strong>5 qualifying trading days</strong> in Stage 2.</p><p>A trading day runs according to the platform's official daily reset period and is counted only when the applicable qualifying trading activity requirement is met.</p><p>After becoming funded, complete <strong>7 trading days</strong> before becoming eligible to request a payout.</p></> },
  { title: 'Maximum Daily Loss', body: <><p>The maximum daily loss is <strong>5% of the initial account balance</strong>.</p><p>Daily loss must remain within the permitted limit during Stage 1, Stage 2, and the Funded Account stage.</p><div className="flash-example-inline"><strong>Example - $10,000 account</strong><span>Maximum permitted daily loss = $500 based on the official daily loss calculation.</span></div></> },
  { title: 'Maximum Total Loss', body: <><p>The maximum total loss is <strong>10% of the initial account balance</strong>.</p><p>The account must remain above the applicable maximum loss threshold throughout Stage 1, Stage 2, and the Funded Account stage.</p><div className="flash-example-inline"><strong>Example - $10,000 account</strong><span>Maximum total loss = $1,000.</span></div></> },
  { title: 'Leverage', body: <><div className="two-step-leverage"><span>Forex <strong>1:100</strong></span><span>Commodities <strong>1:30</strong></span><span>Crypto <strong>1:2</strong></span></div><p>These leverage limits apply across Stage 1, Stage 2, and the Funded Account stage unless otherwise specified.</p></> },
  { title: 'Maximum Risk Per Trade', body: <><p>During the Funded Account stage, the maximum permitted risk per trade is <strong>3% of the initial account balance</strong>.</p><p>Traders are responsible for managing position size, stop loss exposure, and total potential risk. Multiple trades taken on the same asset within the same trading day may be considered together when determining total risk.</p></> },
  { title: 'Trading Period', body: <><p>There is no time limit to complete Stage 1 or Stage 2.</p><p>Traders have unlimited time to reach the applicable profit targets while complying with all trading and account rules.</p></> },
]

const generalRules = [['News Trading', 'Trading around economic news is permitted where the platform and applicable account terms allow it. Deliberate attempts to exploit execution delays, pricing errors, or news straddles are prohibited.'], ['Hedging Within the Same Account', 'Opposing positions within one account are permitted only where they are consistent with the platform and program rules. They must not be used to bypass a loss or risk limit.'], ['Hedging Across Multiple Accounts', 'Coordinated opposite positions across accounts, or activity designed to manufacture a pass or avoid risk, is prohibited.'], ['Expert Advisors / EAs', 'Automated strategies may be used when they do not exploit platform weaknesses, copy another trader, create abusive order traffic, or breach any account condition.'], ['Weekend and Overnight Holding', 'Overnight and weekend positions are permitted unless a specific instrument, platform condition, or account term says otherwise. Traders remain responsible for gaps and resulting drawdown.'], ['High-Frequency Trading', 'Ultra-fast order activity, latency exploitation, quote stuffing, and strategies that depend on execution defects are not permitted. Normal algorithmic trading must remain orderly and risk-controlled.'], ['Toxic Trading Behaviour', 'Abusive patterns such as one-sided betting, grid or martingale exposure, system exploitation, account churning, and reckless position sizing may be treated as a rule violation.'], ['Copy Trading', 'Copying trades between accounts or from another person is not permitted where it creates coordinated or non-independent trading. Each account must reflect the account holder\'s own strategy.'], ['Account Sharing', 'Accounts are personal and may not be shared, managed, sold, or operated by another person.'], ['Payout Eligibility and Window', 'After completing 7 funded trading days and satisfying the applicable requirements, close active positions and submit a request through the available payout process. Payouts remain subject to verification, compliance review, and the applicable payout window.']]
const examples = [['01', 'Passing Stage 1 - 8% Profit', 'A $10,000 Stage 1 account reaches $10,800 after qualifying trades.', 'The 8% target is met. Once the minimum 5 trading-day requirement is also completed and all positions are closed, the trader progresses to Stage 2.'], ['02', 'Passing Stage 2 - 5% Profit', 'A $10,000 Stage 2 account reaches $10,500 after qualifying trades.', 'The 5% target is met. Once the minimum 5 trading-day requirement is also completed and all positions are closed, the trader qualifies to progress to the Funded Account stage.'], ['03', 'Daily Loss Limit', 'A $10,000 account has a 5% daily loss limit.', 'The maximum permitted daily loss is $500 based on the official daily loss calculation.'], ['04', 'Maximum Total Loss', 'A $10,000 account reaches a total loss of $1,000.', 'The 10% maximum total loss limit has been reached.'], ['05', 'Minimum Trading Days', 'A trader completes 5 qualifying trading days in Stage 1.', 'The Stage 1 trading-day requirement is complete. The trader must also complete 5 qualifying trading days in Stage 2 before completing the evaluation requirements.'], ['06', 'Maximum Risk Per Trade', 'A funded $10,000 account has a maximum risk-per-trade limit of 3%.', 'The maximum allowed risk is $300 per trade.'], ['07', 'High-Frequency Trading Violation', 'A strategy repeatedly sends multiple orders in a very short period primarily to exploit latency, quotes, execution delays, or platform weaknesses.', 'The activity may be classified as prohibited high-frequency or abusive trading.'], ['08', 'Tick Scalping / Abusive Execution', 'A trader repeatedly opens and closes trades in an extremely short time primarily to exploit execution behavior rather than execute a genuine trading strategy.', 'The activity may be reviewed as prohibited or abusive trading activity.']]
const faqs = [['What are the profit targets?', 'Stage 1 has an 8% profit target and Stage 2 has a 5% profit target.'], ['How many trading days are required?', 'Complete at least 5 qualifying trading days in Stage 1, 5 in Stage 2, and 7 funded trading days before payout eligibility.'], ['What happens if I hit the daily loss limit?', 'The account must not exceed the applicable 5% daily loss limit based on the platform\'s official calculation and reset methodology.'], ['How is maximum total loss calculated?', 'The maximum total loss is 10% of the initial account balance. The account must remain above the applicable maximum loss threshold.'], ['Can I trade during news?', 'Yes, subject to the existing approved news-trading rules and applicable account conditions.'], ['Can I hold trades overnight?', 'Yes, subject to the existing approved weekend and overnight holding rules and applicable account conditions.'], ['Are Expert Advisors allowed?', 'Yes, subject to the existing approved EA rules and applicable account conditions.'], ['Can I use copy trading?', 'Copy trading remains subject to the existing approved copy-trading rules.'], ['Is there a time limit?', 'There is no time limit to complete Stage 1 or Stage 2. Traders have unlimited time while all rules remain applicable.'], ['When can I request a payout?', 'After completing 7 qualifying trading days during the funded stage and satisfying the applicable payout requirements.'], ['What happens if I violate a rule?', 'A rule violation may result in account restriction, failed evaluation, or loss of payout eligibility under the applicable program terms.']]

export default function TwoStepRulesPage() {
  return <main className="rules-page flash-rules-page two-step-rules-page">
    <div className="rules-page-atmosphere" aria-hidden="true"><span /><span /><i /><i /></div>
    <header className="rules-header"><a href="/" className="brand brand-with-mark"><img src="/fundedwealth-mark.png" alt="FundedWealth Forex mark" /><span>FUNDEDWEALTH <i>FOREX</i></span></a><nav className="rules-nav" aria-label="Primary navigation"><a href="/#challenges">CHALLENGES</a><a href="/#how-it-works">HOW IT WORKS</a><a className="is-active" href="/rules" aria-current="page">RULES</a><a href="/#platforms">PLATFORMS</a><a href="/#faq">FAQ</a></nav><div className="rules-header-actions"><a href="/#community">COMMUNITY</a><a href="/#dashboard">TRADER PORTAL</a><a className="rules-login" href="/#footer">LOGIN / REGISTER</a><LanguageSwitcher /></div></header>
    <RulesHero title="2-Step Challenge Rules" description="Complete two evaluation stages, demonstrate consistency, manage risk responsibly, and qualify for your funded account." ctaText="START EVALUATION" ctaLink="/#challenges" />
    <section className="rules-workspace flash-rules-workspace two-step-content" aria-label="2-Step Challenge rules"><ProgramTabs /><div className="rules-notice"><CircleAlert /><p><strong>Important:</strong> Rule breaches can disqualify an evaluation or restrict a funded account. The applicable program terms and platform records are authoritative.</p></div>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />QUICK RULE OVERVIEW</p><h2>Two stages. One path to funding.</h2><p>Pass Stage 1, demonstrate consistency in Stage 2, and progress to your funded account.</p></div><div className="one-step-overview two-step-overview">{overview.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />HOW IT WORKS</p><h2>A proven path to funding.</h2></div><ol className="one-step-flow two-step-flow">{['Start Stage 1', 'Reach the 8% profit target', 'Complete at least 5 trading days', 'Progress to Stage 2', 'Reach the 5% profit target', 'Complete at least 5 trading days', 'Successfully complete both stages', 'Progress to the Funded Account stage'].map((step, index) => <li key={`${index + 1}-${step}`}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong></li>)}</ol></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />COMPLETE OBJECTIVES</p><h2>Stage 1 to funded account.</h2><p>Compare the requirements at every stage.</p></div><div className="one-step-comparison two-step-comparison"><div className="one-step-comparison-head"><strong>Objective</strong><strong>Stage 1</strong><strong>Stage 2</strong><strong>Funded Account</strong></div>{comparison.map(([label, stageOne, stageTwo, funded]) => <div className="one-step-comparison-row" key={label}><strong>{label}</strong><span data-label="Stage 1">{stageOne}</span><span data-label="Stage 2">{stageTwo}</span><span data-label="Funded Account">{funded}</span></div>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />DETAILED RULES</p><h2>Know the boundaries.</h2></div><div className="flash-rule-grid">{detailedRules.map((rule, index) => <details className="flash-rule-card one-step-detail" key={rule.title} open={index === 0}><summary><span className="flash-rule-number">{String(index + 1).padStart(2, '0')}</span><strong>{rule.title}</strong><span className="one-step-plus" /></summary><div className="flash-rule-content">{rule.body}</div></details>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />GENERAL TRADING RULES</p><h2>Trade with integrity.</h2></div><div className="one-step-general-grid">{generalRules.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />RULE EXAMPLES</p><h2>Rules in practice.</h2><p>Simple $10,000 account scenarios for quick reference.</p></div><div className="one-step-examples two-step-examples">{examples.map(([number, title, scenario, result]) => <article key={number}><span className="flash-rule-number">{number}</span><h3>{title}</h3><div><small>SCENARIO</small><p>{scenario}</p></div><div className="one-step-result"><small>RESULT</small><p>{result}</p></div></article>)}</div></section>
      <section className="one-step-section two-step-faq"><div className="one-step-heading"><p className="rules-kicker"><span />2-STEP FAQ</p><h2>Quick answers.</h2></div><div className="flash-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section><RulesReadyCta program="2-STEP" description="Pass both evaluation stages, demonstrate consistency, and qualify for your funded account." href="/#challenges" /><div className="rules-footnote"><ShieldCheck /><span>These rules are presented for clarity and apply alongside the current FundedWealth Forex Terms, platform conditions, and account-specific requirements.</span></div>
    </section>
  </main>
}
