import type { Metadata } from 'next'
import { CircleAlert, ShieldCheck } from 'lucide-react'
import { LanguageSwitcher } from '@/components/LanguageProvider'
import { RulesHero } from '@/components/RulesHero'
import { ProgramTabs } from '@/components/ProgramTabs'
import { RulesReadyCta } from '@/components/RulesReadyCta'

export const metadata: Metadata = {
  title: '1-Step Challenge Rules | FundedWealth Forex',
  description: 'Explore the complete FundedWealth Forex 1-Step Challenge Rules, including profit targets, drawdown limits, trading requirements, leverage, risk management, payouts, and trading conditions.',
}

const overview = [['10%', 'Profit Target'], ['3 Days', 'Minimum Trading Days\nEvaluation'], ['7 Days', 'Funded Trading Days\nBefore payout eligibility'], ['3%', 'Maximum Daily Loss'], ['6%', 'Maximum Total Loss'], ['3%', 'Maximum Risk Per Trade\nFunded Stage'], ['Unlimited', 'Trading Period'], ['1:30', 'Forex Leverage'], ['1:10', 'Commodities Leverage'], ['1:1', 'Crypto Leverage'], ['80%', 'Funded Profit Split']]
const comparison = [['Virtual Balance', '$5,000 - $100,000', '$5,000 - $100,000'], ['Profit Target', '10%', 'No profit target'], ['Maximum Daily Loss', '3%', '3%'], ['Maximum Total Loss', '6%', '6%'], ['Maximum Risk Per Trade', 'N/A', '3%'], ['Minimum Trading Days', '3 trading days', '7 trading days before payout eligibility'], ['Trading Period', 'Unlimited', 'Unlimited'], ['Forex Leverage', '1:30', '1:30'], ['Commodities Leverage', '1:10', '1:10'], ['Crypto Leverage', '1:1', '1:1'], ['Profit Split', 'N/A', '80%']]

const detailedRules = [
  { title: 'Profit Target', body: <p>Reach a <strong>10% profit target</strong> during the evaluation while remaining within all applicable risk limits.</p> },
  { title: 'Minimum Trading Days', body: <><p>Complete at least <strong>3 qualifying trading days</strong> during the evaluation.</p><p>For the funded stage, complete at least <strong>7 qualifying trading days</strong> before becoming eligible to request a payout.</p></> },
  { title: 'Maximum Daily Loss', body: <><p>The maximum daily loss is <strong>3%</strong>.</p><p>The account must not exceed the applicable daily loss limit based on the platform's official calculation and reset methodology.</p><div className="flash-example-inline"><strong>Example - $10,000 account</strong><span>Maximum permitted daily loss = $300</span></div></> },
  { title: 'Maximum Total Loss', body: <><p>The maximum total loss is <strong>6%</strong>.</p><p>The account equity or balance must not breach the applicable maximum loss threshold.</p><div className="flash-example-inline"><strong>Example - $10,000 account</strong><span>Maximum total loss = $600</span></div></> },
  { title: 'Leverage', body: <div className="one-step-leverage"><span>Forex <strong>1:30</strong></span><span>Commodities <strong>1:10</strong></span><span>Crypto <strong>1:1</strong></span></div> },
  { title: 'Maximum Risk Per Trade', body: <><p>During the Funded stage, maximum risk per trade is <strong>3%</strong>.</p><p>Traders are responsible for managing position size, stop loss exposure, and total potential risk.</p></> },
  { title: 'Trading Period', body: <><p>There is no time limit to complete the evaluation.</p><p>The program allows Unlimited Trading Time while all rules and risk limits remain applicable.</p></> },
]

const generalRules = [['News Trading', 'Trading around economic news is permitted where the platform and applicable account terms allow it. Deliberate attempts to exploit execution delays, pricing errors, or news straddles are prohibited.'], ['Hedging Within the Same Account', 'Opposing positions within one account are permitted only where they are consistent with the platform and program rules. They must not be used to bypass a loss or risk limit.'], ['Hedging Across Multiple Accounts', 'Coordinated opposite positions across accounts, or activity designed to manufacture a pass or avoid risk, is prohibited.'], ['Expert Advisors / EAs', 'Automated strategies may be used when they do not exploit platform weaknesses, copy another trader, create abusive order traffic, or breach any account condition.'], ['Weekend and Overnight Holding', 'Overnight and weekend positions are permitted unless a specific instrument, platform condition, or account term says otherwise. Traders remain responsible for gaps and resulting drawdown.'], ['High-Frequency Trading', 'Ultra-fast order activity, latency exploitation, quote stuffing, and strategies that depend on execution defects are not permitted. Normal algorithmic trading must remain orderly and risk-controlled.'], ['Toxic Trading Behaviour', 'Abusive patterns such as one-sided betting, grid or martingale exposure, system exploitation, account churning, and reckless position sizing may be treated as a rule violation.'], ['Copy Trading', 'Copying trades between accounts or from another person is not permitted where it creates coordinated or non-independent trading. Each account must reflect the account holder\'s own strategy.'], ['Account Sharing', 'Accounts are personal and may not be shared, managed, sold, or operated by another person.'], ['Payout Eligibility and Window', 'After passing, complete 7 funded trading days, close active positions, and submit a request through the available payout process. Payouts remain subject to verification, compliance review, and the applicable payout window.']]
const examples = [['01', 'Hitting the 10% Target to Pass', 'A $10,000 evaluation reaches $11,000 after qualifying trades.', 'The 10% target is met.'], ['02', 'Daily Loss Limit', 'A $10,000 account has a 3% daily loss limit.', 'The maximum permitted daily loss is $300 based on the official calculation method.'], ['03', 'Maximum Total Loss', 'A $10,000 account reaches a total loss of $600.', 'The 6% maximum total loss limit has been reached.'], ['04', 'Minimum Trading Days', 'Complete at least 3 qualifying trading days during evaluation.', 'The evaluation trading-day requirement is completed.'], ['05', 'Maximum Risk Per Trade', 'A funded $10,000 account has a maximum risk-per-trade limit of 3%.', 'Maximum allowed risk is $300 per trade.'], ['06', 'High-Frequency Trading Violation', 'Strategies designed to exploit latency, quotes, execution delays, or platform weaknesses are prohibited.', 'The strategy is prohibited.'], ['07', 'Tick Scalping / Abusive Execution', 'Repeated ultra-short trades designed primarily to exploit execution behavior may be reviewed as prohibited trading activity.', 'The activity may be reviewed as prohibited trading.']]
const faqs = [['What is the profit target?', 'The evaluation profit target is 10%.'], ['What happens if I hit the daily loss limit?', 'The account must not exceed the applicable 3% daily loss limit based on the platform\'s official calculation and reset methodology.'], ['How is maximum total loss calculated?', 'The maximum total loss is 6%. The account equity or balance must not breach the applicable maximum loss threshold.'], ['Can I trade during news?', 'Yes, subject to the existing approved news-trading rules and applicable account conditions.'], ['Can I hold trades overnight?', 'Yes, subject to the existing approved weekend and overnight holding rules and applicable account conditions.'], ['Are Expert Advisors allowed?', 'Yes, subject to the existing approved EA rules and applicable account conditions.'], ['Can I use copy trading?', 'Copy trading remains subject to the existing approved copy-trading rules.'], ['How many trading days are required?', 'Complete at least 3 qualifying trading days during evaluation and 7 qualifying funded trading days before payout eligibility.'], ['Is there a time limit?', 'There is no time limit to complete the evaluation. The program allows Unlimited Trading Time while all rules and risk limits remain applicable.'], ['When can I request a payout?', 'After completing at least 7 qualifying trading days during the funded stage and satisfying the applicable payout requirements.'], ['What happens if I violate a rule?', 'A rule violation may result in account restriction, failed evaluation, or loss of payout eligibility under the applicable program terms.']]

export default function OneStepRulesPage() {
  return <main className="rules-page flash-rules-page one-step-rules-page">
    <header className="rules-header"><a href="/" className="brand brand-with-mark"><img src="/fundedwealth-mark.png" alt="FundedWealth Forex mark" /><span>FUNDEDWEALTH <i>FOREX</i></span></a><nav className="rules-nav" aria-label="Primary navigation"><a href="/#challenges">CHALLENGES</a><a href="/#how-it-works">HOW IT WORKS</a><a className="is-active" href="/rules" aria-current="page">RULES</a><a href="/#platforms">PLATFORMS</a><a href="/#faq">FAQ</a></nav><div className="rules-header-actions"><a href="/#community">COMMUNITY</a><a href="/#dashboard">TRADER PORTAL</a><a className="rules-login" href="/#footer">LOGIN / REGISTER</a><LanguageSwitcher /></div></header>
    <RulesHero title="1-Step Challenge Rules" description="Complete one evaluation phase, meet the objectives, manage risk responsibly, and qualify for your funded account." ctaText="START EVALUATION" ctaLink="/#challenges" />
    <section className="rules-workspace flash-rules-workspace one-step-content" aria-label="1-Step Challenge rules"><ProgramTabs /><div className="rules-notice"><CircleAlert /><p><strong>Important:</strong> Rule breaches can disqualify an evaluation or restrict a funded account. The applicable program terms and platform records are authoritative.</p></div>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />QUICK RULE OVERVIEW</p><h2>The objective, at a glance.</h2><p>One evaluation. Clear risk parameters. Unlimited time to execute with discipline.</p></div><div className="one-step-overview">{overview.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />HOW IT WORKS</p><h2>A focused path to funding.</h2></div><ol className="one-step-flow">{['Start the 1-Step Evaluation', 'Reach the 10% profit target', 'Complete at least 3 trading days', 'Respect drawdown and trading rules', 'Successfully complete the evaluation', 'Progress to the Funded Account stage'].map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, '0')}</span><strong>{step}</strong></li>)}</ol></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />COMPLETE OBJECTIVES</p><h2>Evaluation to funded account.</h2><p>Compare the requirements at each stage.</p></div><div className="one-step-comparison"><div className="one-step-comparison-head"><strong>Objective</strong><strong>Evaluation</strong><strong>Funded Account</strong></div>{comparison.map(([label, evaluation, funded]) => <div className="one-step-comparison-row" key={label}><strong>{label}</strong><span data-label="Evaluation">{evaluation}</span><span data-label="Funded Account">{funded}</span></div>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />DETAILED RULES</p><h2>Know the boundaries.</h2></div><div className="flash-rule-grid">{detailedRules.map((rule, index) => <details className="flash-rule-card one-step-detail" key={rule.title} open={index === 0}><summary><span className="flash-rule-number">{String(index + 1).padStart(2, '0')}</span><strong>{rule.title}</strong><span className="one-step-plus" /></summary><div className="flash-rule-content">{rule.body}</div></details>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />GENERAL TRADING RULES</p><h2>Trade with integrity.</h2></div><div className="one-step-general-grid">{generalRules.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
      <section className="one-step-section"><div className="one-step-heading"><p className="rules-kicker"><span />RULE EXAMPLES</p><h2>Rules in practice.</h2><p>Simple $10,000 account scenarios for quick reference.</p></div><div className="one-step-examples">{examples.map(([number, title, scenario, result]) => <article key={number}><span className="flash-rule-number">{number}</span><h3>{title}</h3><div><small>SCENARIO</small><p>{scenario}</p></div><div className="one-step-result"><small>RESULT</small><p>{result}</p></div></article>)}</div></section>
      <section className="one-step-section one-step-faq"><div className="one-step-heading"><p className="rules-kicker"><span />1-STEP FAQ</p><h2>Quick answers.</h2></div><div className="flash-faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section><RulesReadyCta program="1-STEP" description="Complete one evaluation phase, meet your objectives, and qualify for your funded account." href="/#challenges" /><div className="rules-footnote"><ShieldCheck /><span>These rules are presented for clarity and apply alongside the current FundedWealth Forex Terms, platform conditions, and account-specific requirements.</span></div>
    </section></main>
}